### ISSUE TITLE
[BUG] Changing gender to "female" not working correctly.

### ISSUE THREAD

**Issue by DarkKingKaan** [ThePlay3r/Marriage#1]
When you set your gender to female (/marry gender Female), it first changes your gender to "None", then to "Male".

https://i.imgur.com/zx3qoFh.png

Reproduction:
- Execute /marry gender female

Here is a screenshot:
https://i.imgur.com/zx3qoFh.png

**Comment by ThePlay3r** [comment]
Thanks for reporting the issue!
Fixed in the latest [Version 1.5](https://github.com/ThePlay3r/Marriage/releases/tag/1.5) of the plugin.
