### ISSUE TITLE
Missing database columns 

### ISSUE THREAD

**Issue by iLuckyx** [ThePlay3r/Marriage#10]
Hey,

My players have been running into issues with their partners continuously being reset. After looking into it for a bit, I see that every time a player logs in or out, console gets filled with the error outlined in the pastebin. I also get some errors on startup. I'm running the latest 2.1 version hoping that may have fixed it. I've dropped the table entirely within the database, still no luck, 

[console startup errors]
https://pastebin.com/FgXVmYh8

[each time a player leaves / joins]
https://pastebin.com/yvU6aqhx

If more information / testing is needed, feel free to contact me at anytime on discord: xLucky#1475 

FYI, we use MYSQL. 

![image](https://user-images.githubusercontent.com/35910221/108825401-f7ea4d00-7590-11eb-9664-1dd4b2c3f4d3.png)

Screenshot shows the columns created. FYI the partnerID column was just partner, I manually changed it to partnerID to see if it would change anything, it broke the plugin :P 

Kind Regards,
Lucky

**Comment by ThePlay3r** [comment]
You are using old (Version 1.7.1) table structure. You need to let the plugin generate a new one by dropping the `marriage_players` table entirely.

**Comment by iLuckyx** [comment]
Dropped the table entirely, let it refresh and the issue has been resolved <3 Thank you
