### ISSUE TITLE
Some commands aren't working

### ISSUE THREAD

**Issue by Drakunovu** [ThePlay3r/Marriage#11]
Hello, the commands:
/marry c
/marry gender

aren't working, my server version is 1.14.4 PaperSpigot
Latest version of the plugin and the dependency, using MySQL Database

**Comment by ThePlay3r** [comment]
How exactly does `/marry c` not work? Are there any errors, or does it say nothing at all?

**Comment by Drakunovu** [comment]
So, it is like you write /marry c and it is going to marry the player named "c", same for gender and same for gift.
