### ISSUE TITLE
A guide to Placeholders? I can't figure out how to use them.

### ISSUE THREAD

**Issue by DarkKingKaan** [ThePlay3r/Marriage#2]
I cannot figure out how the placeholders are supposed to work.

I use EssentialsX for chat formatting and I can't figure out how to use the Placeholders.
I have installed PlaceholderAPI and all the things it needs to run, could you possibly explain how to use them in a Wiki?

This is what I'm trying to accomplish:
%heart_symbol% (if married) %gender_symbol% <playername> <message>

Thank you in advance for your answer.

**Comment by ThePlay3r** [comment]
All the placeholders are **already** listed on the [Wiki](https://github.com/ThePlay3r/Marriage/wiki/Placeholders).

If you have PlaceholderAPI, PLJRApi and Marriage on your server, only thing you need to do is to enable PAPI support in the [PLJRApi's configuration](https://github.com/ThePlay3r/PLJRApi/blob/master/src/main/resources/config.yml#L45).

You then can try, if the placeholders work, by (for example) running this command:
`/papi parse me %marriage_gender%`
