### ISSUE TITLE
Using placeholders throws error to console

### ISSUE THREAD

**Issue by DarkKingKaan** [ThePlay3r/Marriage#3]
Hello there,

I tried to use placeholders by following the instructions stated in the previous issue:
https://github.com/ThePlay3r/Marriage/issues/2

I think I did everything correctly but I got this error:
https://pastebin.com/zexGJX7n

I have all - PlaceholderAPI, PLJRApi, and Marriage - on my server and I have enabled the placeholders in PLJRApi configuration, too.

Thank you for your answer. 👋

**Comment by ThePlay3r** [comment]
`Caused by: java.lang.ClassNotFoundException: com.lenis0012.bukkit.marriage2.internal.MarriagePlugin`

PlaceholderAPI is trying to load class from [another Marriage plugin](https://api.extendedclip.com/expansions/marriage/) (not mine), you will have to remove the expansion in order to fix this issue.

**Comment by DarkKingKaan** [comment]
I have removed the expansion. I didn't realize that this wasn't your plugin.
As you stated in https://github.com/ThePlay3r/Marriage/issues/2, I, for example, have to use "/papi parse me %marriage_gender%" command after everything is set up, but it doesn't seem to work at all. I just get this message:

https://i.imgur.com/sJcFNso.png

Placeholders just don't work for me. I've been trying for days now. If you have any idea what could be causing this, please let me know.

Thanks.

**Comment by ThePlay3r** [comment]
That's weird, it works just fine for me.

What server version are you running? Also, are there any errors in the console, when trying to run the command ? Your PLJRApi configuration file would also be helpful (but be sure to post it without the MySQL credentials).

It would also be more efficient if you contacted me on Discord, or gave me the IP Address of the server, so we can try various things to fix it faster.

**Comment by DarkKingKaan** [comment]
I am running the latest Paper. There are no errors in the console.
Here is the configuration file: https://pastebin.com/U6wuzueN.

I agree to switch this conversation to Discord. Do you have a specific server or should we do it in DMs?
My Discord username is DarkKingKaan#3507.

Thanks.

**Comment by DarkKingKaan** [comment]
Unbelievable. I did **absolutely nothing** and it just started working. I don't understand this. I would still like to have your Discord for any more problems. Thank you for your time.

Have a nice day!
