### ISSUE TITLE
Spy bug

### ISSUE THREAD

**Issue by SmigloNPC** [ThePlay3r/Marriage#4]
When I have spy activated I don't see message from marriage chat. <br>But on server logs I see that /marry c have been used by players<br>
I have all permission on server and there is no errors on console

**Comment by ThePlay3r** [comment]
I'm sorry for the inconvenience.

I found the cause of the issue and will fix it in the upcoming weekend, for now, I would recommend **not using** the spy feature at all.

**Comment by ThePlay3r** [comment]
Fixed in the [1.7 version](https://github.com/ThePlay3r/Marriage/releases/tag/1.7).
