### ISSUE TITLE
(1.15.2) Error on player join and random database errors

### ISSUE THREAD

**Issue by DarkKingKaan** [ThePlay3r/Marriage#5]
Here's the error I'm getting on player join:
https://pastebin.com/1u4qJDBA

I'm also experiencing cases where the plugin isn't able to connect to the database for some reason (I use PLJRApi for database connections). All other plugins that use the database work just fine. This means players sometimes cannot connect to the server.

Thank you in advance for your help.

**Comment by ThePlay3r** [comment]
Fixed in the [1.7.1 Version](https://github.com/ThePlay3r/Marriage/releases/tag/1.7.1).
Just make sure you have correctly set the default home in the configuration, the error you are having should be very rare.
