### ISSUE TITLE
(Error) Exception on player connect/disconnect.

### ISSUE THREAD

**Issue by DarkKingKaan** [ThePlay3r/Marriage#6]
Here's the error: https://pastebin.com/RKubfg57

Sometimes players can't connect to the server. The server's running fine but can't really handle player connections. Works for a short time after restarting.

I'm using the latest Paper 1.15.2. Any way to fix this?

Thank you in advance for your help.

**Comment by ThePlay3r** [comment]
Do you have your default home set correctly? (Mainly the name of the world)

**Comment by ThePlay3r** [comment]
Project completely recoded from scratch. ([v2.0](https://github.com/ThePlay3r/Marriage/releases/tag/v2.0))
