### ISSUE TITLE
Bugs after recode

### ISSUE THREAD

**Issue by SmigloNPC** [ThePlay3r/Marriage#9]
Hello
After plugin recode, I found a few bugs:
- players can't kiss their partners (any interact don't work)
- on marry chat players can send only 1 word
- on marry gift (bug report from player) plugin can take things from more than one slot, but partner receive things from only one slot
- /amarry without args sends error [https://prnt.sc/102yc9x](https://prnt.sc/102yc9x)
- /amarry spy doesn't enable and disable spying (default spying is enabled)
- /amarry unmarry and /amarry marry don't send broadcast that players marriaged or divorced
- /amarry xp enable/disable PvP and /amarry pvp enable/disable xp share

**Comment by ThePlay3r** [comment]
Thanks for reporting those errors!
Everything should be fixed in the [version 2.1](https://github.com/ThePlay3r/Marriage/releases/tag/v2.1).
